// dashboard/src/lib/areas.ts — generated by setup-customize
// Edit this file to update room/entity mappings. Re-run setup-customize to regenerate.

export interface ZoneOccupancy {
  entity: string;
  label: string;
}

export interface ContactSensor {
  entity: string;
  label: string;
  type?: "door" | "window";
}

export interface RoomConfig {
  id: string;
  name: string;
  floor: number;
  icon: string;

  // Lighting
  light?: string;           // primary light group entity
  lights: string[];         // all controllable lights in the room

  // Presence
  occupancySensor?: string;
  zoneOccupancy?: ZoneOccupancy[];

  // Environment
  temperatureSensor?: string;
  humiditySensor?: string;
  co2Sensor?: string;
  illuminanceSensor?: string;
  noiseSensor?: string;
  pressureSensor?: string;
  aqiSensor?: string;
  temperatureRate?: string;

  // Climate
  climate?: string[];       // TRV or AC entity IDs
  effectiveTarget?: string; // template sensor for effective target temp

  // Media
  mediaPlayers?: string[];
  remoteEntity?: string;
  /** TV platform for adapter-based remote control (fire_tv, androidtv, roku, apple_tv) */
  tvPlatform?: string;
  /** Override volume control entity (e.g. a soundbar separate from the TV) */
  volumeEntity?: string;
  /** timer.* entity for TV sleep timer */
  sleepTimer?: string;

  // Security
  contactSensors?: ContactSensor[];
  camera?: string;

  // Covers/blinds
  covers?: string[];
}

// Floor level constants
const MAIN = 0;
const UPPER = 1;
const BASEMENT = -1;

export const ROOMS: RoomConfig[] = [
  {
    id: "living_room",
    name: "Living Room",
    floor: MAIN,
    icon: "mdi:sofa",
    light: "light.living_room",
    lights: ["light.living_room", "light.lr_table_lamp", "light.lr_floor_lamp"],
    occupancySensor: "binary_sensor.hue_motion_lr_occupancy",
    temperatureSensor: "sensor.hue_motion_lr_temperature",
    illuminanceSensor: "sensor.hue_motion_lr_illuminance",
    mediaPlayers: ["media_player.nesthub7a14_2"],
  },
  {
    id: "kitchen",
    name: "Kitchen",
    floor: MAIN,
    icon: "mdi:stove",
    lights: [],
  },
  {
    id: "dining_room",
    name: "Dining Room",
    floor: MAIN,
    icon: "mdi:table-furniture",
    lights: [],
  },
  {
    id: "front_entry",
    name: "Front Entry",
    floor: MAIN,
    icon: "mdi:door-closed",
    lights: [],
    occupancySensor: "binary_sensor.g4_instant_frontporch_motion",
    camera: "camera.g4_instant_frontporch_high_resolution_channel",
    contactSensors: [
      { entity: "binary_sensor.front_door_contact", label: "Front Door", type: "door" },
    ],
  },
  {
    id: "garage",
    name: "Garage",
    floor: MAIN,
    icon: "mdi:garage",
    lights: [],
    occupancySensor: "binary_sensor.g4_instant_garage_motion",
    camera: "camera.g4_instant_garage_high_resolution_channel",
    contactSensors: [
      { entity: "binary_sensor.garage_door_contact", label: "Garage Door", type: "door" },
      { entity: "binary_sensor.garage_overhead_door", label: "Overhead Door", type: "door" },
    ],
  },
  {
    id: "stairwell",
    name: "Stairwell",
    floor: MAIN,
    icon: "mdi:stairs",
    light: "light.night_light_stairwell",
    lights: ["light.night_light_stairwell"],
    occupancySensor: "binary_sensor.night_light_stairwell_occupancy",
  },
  {
    id: "primary_bedroom",
    name: "Primary Bedroom",
    floor: UPPER,
    icon: "mdi:bed-king",
    light: "light.primary_bedroom",
    lights: [
      "light.primary_bedroom",
      "light.primary_bdrm_lamp_2",
    ],
    temperatureSensor: "sensor.wave_enhance_master_br_temperature",
    humiditySensor: "sensor.wave_enhance_master_br_humidity",
    co2Sensor: "sensor.wave_enhance_master_br_carbon_dioxide",
    noiseSensor: "sensor.wave_enhance_master_br_sound_pressure",
    pressureSensor: "sensor.wave_enhance_master_br_atmospheric_pressure",
    illuminanceSensor: "sensor.wave_enhance_master_br_illuminance",
    mediaPlayers: ["media_player.master_bedroom_wifi"],
  },
  {
    id: "kennedys_bedroom",
    name: "Kennedy's Bedroom",
    floor: UPPER,
    icon: "mdi:bed",
    light: "light.kennedys_bedroom",
    lights: ["light.kennedys_bedroom", "light.kennedy_light_bar"],
    mediaPlayers: ["media_player.kennedys_bedroom"],
  },
  {
    id: "zaviers_bedroom",
    name: "Zavier's Bedroom",
    floor: UPPER,
    icon: "mdi:bed",
    lights: [],
    mediaPlayers: ["media_player.zaviers_bedroom_speaker"],
  },
  {
    id: "laundry_room",
    name: "Laundry Room",
    floor: UPPER,
    icon: "mdi:washing-machine",
    lights: [],
  },
  {
    id: "family_room",
    name: "Family Room",
    floor: BASEMENT,
    icon: "mdi:sofa-outline",
    light: "light.family_room",
    lights: [
      "light.family_room",
      "light.family_room_floor_lamp_1",
      "light.fr_lamp_1",
      "light.fr_lamp_2",
      "light.fr_lamp_3",
    ],
    temperatureSensor: "sensor.view_plus_basement_temperature",
    humiditySensor: "sensor.view_plus_basement_humidity",
    co2Sensor: "sensor.view_plus_basement_carbon_dioxide",
    pressureSensor: "sensor.view_plus_basement_atmospheric_pressure",
    aqiSensor: "sensor.view_plus_basement_volatile_organic_compounds_parts",
    mediaPlayers: ["media_player.family_room_wifi", "media_player.family_room_speaker"],
  },
  {
    id: "office",
    name: "Office",
    floor: BASEMENT,
    icon: "mdi:desk",
    light: "light.office_lamp",
    lights: ["light.office_lamp"],
  },
];

// Maps HA person display name (lowercase) → room id for pinning
export const USER_ROOM_MAP: Record<string, string> = {
  // "phillip": "office",
  // "kristine": "primary_bedroom",
};
